spring:
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none