spring:
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://localhost:5432/crud
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: tuyenquanghpkt@gmail.com # Thay bằng email của bạn
    password: bnkt znlx efqp jcha # Thay bằng app password từ Google
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
